apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kubernetes-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-kubernetes-example
  template:
    metadata:
      labels:
        app: node-kubernetes-example
    spec:
      containers:
      - name: node-kubernetes-example
        args: [ "node ./dist/index.js" ]
        command: [ "sh", "-c" ]
        image: 'kubernetes_app'
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-kubernetes-example-entrypoint
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-kubernetes-example